load("@pip_deps//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_library", "py_test")

package(default_visibility=["//visibility:public"])

py_library(
    name="data",
    srcs=glob(
        ["*.py"],
        exclude=["*_test.py"],
    ),
    imports=["../.."],
    deps=[
        "//agent/utils:utils",
        requirement("beautifulsoup4"),
        requirement("pandas"),
        requirement("requests"),
        requirement("yfinance"),
    ],
)

py_test(
    name="fundamentals_test",
    srcs=["fundamentals_test.py"],
    main="fundamentals_test.py",
    legacy_create_init=False,
    imports=["../.."],
    deps=[
        ":data",
        "//:agent",
    ],
)

py_test(
    name="news_crawler_test",
    srcs=["news_crawler_test.py"],
    main="news_crawler_test.py",
    legacy_create_init=False,
    imports=["../.."],
    deps=[
        ":data",
        "//:agent",
    ],
)

py_test(
    name="sec_filings_test",
    srcs=["sec_filings_test.py"],
    main="sec_filings_test.py",
    legacy_create_init=False,
    imports=["../.."],
    deps=[
        ":data",
        "//:agent",
    ],
)

py_test(
    name="sp500_analyzer_test",
    srcs=["sp500_analyzer_test.py"],
    main="sp500_analyzer_test.py",
    legacy_create_init=False,
    imports=["../.."],
    deps=[
        ":data",
        "//:agent",
    ],
)
